### ISSUE TITLE
よかった！

### ISSUE THREAD

**Issue by ken1flan** [ginzarb/zagin_stamps#25]
っていう返事用の絵がほしい。

**Comment by y-yagi** [comment]
![good](https://cloud.githubusercontent.com/assets/987638/17426033/e2b34cc6-5b0e-11e6-88de-632792e89f68.png)
(昔こんなの用意してたの思い出した)

**Comment by ken1flan** [comment]
![よかったにゃ](https://raw.githubusercontent.com/ginzarb/zagin_stamps/master/thats_great/mike_stamp.png)

**Comment by ken1flan** [comment]
だん。
